language: node_js
node_js:
- '0.10'
before_install:
  - npm install npm -g
before_deploy:
  - npm install ws browserify coffeeify
  - mkdir -p deploy/meshblu-rolling-spider/latest
  - mkdir -p deploy/meshblu-rolling-spider/$TRAVIS_TAG
  - node_modules/.bin/browserify -t coffeeify -s Connector connector.js > deploy/meshblu-rolling-spider/latest/meshblu-rolling-spider.js
  - gzip deploy/meshblu-rolling-spider/latest/meshblu-rolling-spider.js
  - mv deploy/meshblu-rolling-spider/latest/meshblu-rolling-spider.js.gz deploy/meshblu-rolling-spider/latest/meshblu-rolling-spider.js
  - cp deploy/meshblu-rolling-spider/latest/meshblu-rolling-spider.js deploy/meshblu-rolling-spider/$TRAVIS_TAG/meshblu-rolling-spider.js
deploy:
  - provider: s3
    region: us-west-2
    skip_cleanup: true
    detect_encoding: true
    access_key_id: replace-me
    secret_access_key:
      secure: replace-me
    bucket: octoblu-cdn
    local-dir: deploy
    upload-dir: js
    on:
      tags: true
      all_branches: true
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: replace-me
    api_key:
      secure: replace-me
    on:
      tags: true
      all_branches: true
